apiVersion: run.ai/v1
kind: RunaiJob
metadata:
  name: invariant-sa-train
  namespace: runai-imos-awei
  labels:
    user: awei
spec:
  template:
    metadata:
      labels:
        user: awei
        release: invariant-sa-train
    spec:
      schedulerName: runai-scheduler
      restartPolicy: Never
      securityContext:
        runAsUser: 158255
        runAsGroup: 79821 # GID is imos-rcp-staff
        fsGroup: 79821 # GID is imos-rcp-staff
      containers:
        - name: nvidia-jax-2310-py3
          image: registry.rcp.epfl.ch/imos-awei/nvidia-jax-23.10-py3:latest
          imagePullPolicy: Always
          workingDir: /home/awei
          command: ["/bin/bash", "-c"]
          args:
            - |
              LOG_DIR=${PVC_DIR}/logs/invariant-sa/$(date '+%Y-%m-%d')/
              git clone git@github.com:AmauryWEI/phd-google-code.git
              cd phd-google-code
              ./invariant_slot_attention/run.sh $LOG_DIR
          env:
            - name: WANDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wandb-secret
                  key: secret
            - name: PVC_DIR
              value: /mnt/runai-imos-awei-scratch/imos-staff/awei/
            - name: TETROMINOES_ROOT_DIR
              value: /mnt/runai-imos-awei-scratch/imos-staff/awei/datasets/Tetrominoes/
            - name: CLEVR_ROOT_DIR
              value: /mnt/runai-imos-awei-scratch/imos-staff/awei/datasets/CLEVR_with_masks/
          resources:
            limits:
              nvidia.com/gpu: 1
          volumeMounts:
            - mountPath: /dev/shm
              name: dshm
            - mountPath: /mnt/runai-imos-awei-scratch/
              name: runai-imos-awei-scratch
      imagePullSecrets:
        - name: awei-pull-robot-secret
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        - name: runai-imos-awei-scratch
          persistentVolumeClaim:
            claimName: runai-imos-awei-scratch
